{{- if .Values.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "benthos.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "benthos.labels" . | nindent 4 }}
data:
  benthos.yaml: |-
{{ tpl .Values.config . | nindent 4 }}
{{- end -}}