{{- if .Values.http.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "benthos.fullname" . }}
  labels:
    {{- include "benthos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    -
      {{- range $key, $val := . }}
      {{ $key }}: {{ tpl (toString $val) $ }}
      {{- end }}
  {{- end }}
  selector:
    {{- include "benthos.selectorLabels" . | nindent 4 }}
{{- end -}}
