{{- if .Values.http.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benthos.fullname" . }}-tls
type: kubernetes.io/tls
data: 
  tls.crt: |
    {{ .Files.Get .Values.http.tls.cert_file | b64enc }}
  tls.key: |
    {{ .Files.Get .Values.http.tls.key_file | b64enc }}
{{- end -}}